package com.AISA.AISA.kisStock.scheduler;

import com.AISA.AISA.kisStock.enums.OverseasIndex;
import com.AISA.AISA.kisStock.kisService.KisStockService;
import com.AISA.AISA.kisStock.kisService.KisIndexService;
import com.AISA.AISA.kisStock.kisService.KisMacroService;
import com.AISA.AISA.kisStock.enums.ExchangeRateCode;
import com.AISA.AISA.kisStock.enums.BondYield;
import com.AISA.AISA.portfolio.macro.service.EcosService;
import com.AISA.AISA.kisStock.kisService.DividendService;
import com.AISA.AISA.kisStock.kisService.KisInformationService;
import com.AISA.AISA.kisStock.kisService.Auth.KisAuthService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.FileSystemResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;

@Component
@RequiredArgsConstructor
@Slf4j
public class StockScheduler {

    private final KisStockService kisStockService;
    private final KisIndexService kisIndexService;
    private final KisMacroService kisMacroService;
    private final EcosService ecosService;
    private final DividendService dividendService;
    private final KisInformationService kisInformationService;
    private final KisAuthService kisAuthService;
    private final DataSource dataSource;

    // Run at 2 AM every day
    @Scheduled(cron = "0 0 2 * * *")
    public void updateAllStockData() {
        log.info("Starting scheduled stock data update...");

        // Fetch data for the last 3 years (approx 1000 days)
        LocalDate targetStartDate = LocalDate.now().minusYears(3);
        String targetStartDateStr = targetStartDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"));

        kisStockService.fetchAllStocksHistoricalData(targetStartDateStr);

        log.info("Completed scheduled stock data update.");
    }

    // Run at 3 AM every day (Stock List Crawling)
    @Scheduled(cron = "0 0 3 * * *")
    public void crawlAndInsertStocks() {
        log.info("Starting scheduled stock list crawling...");
        Path tempDir = null;
        try {
            // 1. Setup Temp Directory
            tempDir = Files.createTempDirectory("stock_crawler");
            File scriptFile = tempDir.resolve("crawl_stocks.py").toFile();

            // 2. Copy Python Script from Classpath
            try (InputStream is = new ClassPathResource("scripts/crawl_stocks.py").getInputStream()) {
                Files.copy(is, scriptFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            }

            // 3. Run Python Process
            ProcessBuilder pb = new ProcessBuilder("python", scriptFile.getAbsolutePath()); // Expects 'python' in PATH
            pb.directory(tempDir.toFile()); // Run in temp dir so stocks.sql is created there
            pb.redirectErrorStream(true);
            Process process = pb.start();

            // Capture logs
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    log.info("[Python] " + line);
                }
            }

            int exitCode = process.waitFor();
            if (exitCode != 0) {
                log.error("Python script failed with exit code: " + exitCode);
                return;
            }

            // 4. Validate Generated SQL File
            File sqlFile = tempDir.resolve("stocks.sql").toFile();
            if (!sqlFile.exists()) {
                log.error("stocks.sql was not generated by the Python script.");
                return;
            }

            // 5. Execute SQL Script
            try (Connection conn = dataSource.getConnection()) {
                ScriptUtils.executeSqlScript(conn, new FileSystemResource(sqlFile));
                log.info("Successfully executed stocks.sql script.");
            }

        } catch (Exception e) {
            log.error("Failed to run python crawling task", e);
        } finally {
            // Cleanup
            if (tempDir != null) {
                try {
                    // Simple cleanup - deletes the dir if empty or files within
                    // java.io.File delete() only works for empty dirs.
                    // Recursively delete or just let OS handle temp?
                    // Best effort cleanup
                    Files.walk(tempDir)
                            .sorted(Comparator.reverseOrder())
                            .map(Path::toFile)
                            .forEach(File::delete);
                } catch (Exception ignored) {
                }
            }
        }
        log.info("Completed scheduled stock list crawling.");
    }

    // Run at 10 AM every day (After US market close)
    @Scheduled(cron = "0 0 10 * * *")
    public void updateOverseasIndexData() {
        log.info("Starting scheduled overseas index data update...");

        // Fetch data for the last 7 days to ensure recent data is captured
        LocalDate endDate = LocalDate.now();
        LocalDate startDate = endDate.minusDays(7);
        String endDateStr = endDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"));
        String startDateStr = startDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"));

        for (OverseasIndex index : OverseasIndex.values()) {
            try {
                kisIndexService.fetchAndSaveOverseasIndex(index, startDateStr, endDateStr);
                Thread.sleep(1000); // Reduce API load
            } catch (Exception e) {
                log.error("Failed to update overseas index: {}", index, e);
            }
        }
        log.info("Completed scheduled overseas index data update.");
    }

    // Run at 4 PM every day (After Korean market close)
    @Scheduled(cron = "0 0 16 * * *")
    public void updateExchangeRateData() {
        log.info("Starting scheduled exchange rate data update...");

        // Fetch data for the last 7 days
        LocalDate endDate = LocalDate.now();
        LocalDate startDate = endDate.minusDays(7);
        String endDateStr = endDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"));
        String startDateStr = startDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"));

        // 1. Update Basic Rates (USD, JPY, HKD, EUR)
        // JPY, HKD, EUR will be fetched as defined in ExchangeRateCode
        for (ExchangeRateCode code : ExchangeRateCode.values()) {
            if (code == ExchangeRateCode.HKD_KRW || code == ExchangeRateCode.EUR_KRW) {
                continue; // Skip calculated rates for now
            }
            try {
                kisMacroService.fetchAndSaveExchangeRate(code.getSymbol(), startDateStr, endDateStr);
                Thread.sleep(500); // Rate limit
            } catch (Exception e) {
                log.error("Failed to update exchange rate for {}: {}", code, e.getMessage());
            }
        }

        // 2. Update Calculated Rates (HKD/KRW, EUR/KRW)
        try {
            kisMacroService.calcAndSaveHkdKrwRate(startDateStr, endDateStr);
            Thread.sleep(100);
            kisMacroService.calcAndSaveEurKrwRate(startDateStr, endDateStr);
        } catch (Exception e) {
            log.error("Failed to calculate cross rates: {}", e.getMessage());
        }

        log.info("Completed scheduled exchange rate data update.");
    }

    // Run at 4:05 PM every day (After Exchange Rate update)
    @Scheduled(cron = "0 5 16 * * *")
    public void updateBondYieldData() {
        log.info("Starting scheduled bond yield data update...");

        LocalDate endDate = LocalDate.now();
        LocalDate startDate = endDate.minusDays(7);
        String endDateStr = endDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"));
        String startDateStr = startDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"));

        for (BondYield bond : BondYield.values()) {
            try {
                kisMacroService.fetchAndSaveBondYield(bond, startDateStr, endDateStr);
                Thread.sleep(500); // Rate limit
            } catch (Exception e) {
                log.error("Failed to update bond yield for {}: {}", bond, e.getMessage());
            }
        }
        log.info("Completed scheduled bond yield data update.");
    }

    // Run at 9 AM on the 1st of every month
    @Scheduled(cron = "0 0 9 1 * *")
    public void updateMonthlyMacroData() {
        log.info("Starting scheduled monthly macro data update...");

        // Fetch data for the last 2 months to ensure recent data is captured
        LocalDate endDate = LocalDate.now();
        LocalDate startDate = endDate.minusMonths(2);
        String endDateStr = endDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"));
        String startDateStr = startDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"));

        try {
            ecosService.saveM2Data(startDateStr, endDateStr);
            Thread.sleep(500);
            ecosService.saveBaseRate(startDateStr, endDateStr);
            Thread.sleep(500);
            ecosService.saveCPI(startDateStr, endDateStr);
        } catch (Exception e) {
            log.error("Failed to update monthly macro data: {}", e.getMessage());
        }

        log.info("Completed scheduled monthly macro data update.");
    }

    // Run at 5 AM every Friday (For ECOS Bond Yield)
    @Scheduled(cron = "0 0 5 * * FRI")
    public void updateWeeklyEcosData() {
        log.info("Starting scheduled weekly ECOS data (Bond Yield) update...");
        try {
            kisMacroService.fetchAndSaveEcosBondYield();
        } catch (Exception e) {
            log.error("Failed to update weekly ECOS data: {}", e.getMessage());
        }
        log.info("Completed scheduled weekly ECOS data update.");
    }

    // Run at 00:00 every day (Daily Token Refresh)
    @Scheduled(cron = "0 0 0 * * *")
    public void refreshKisAccessToken() {
        log.info("Starting scheduled KIS Access Token refresh...");
        try {
            kisAuthService.refreshAccessToken();
        } catch (Exception e) {
            log.error("Failed to refresh KIS Access Token: {}", e.getMessage());
        }
        log.info("Completed scheduled KIS Access Token refresh.");
    }

    // Run at 5 AM every Saturday
    @Scheduled(cron = "0 0 5 * * SAT")
    public void refreshDividendDataAndRank() {
        log.info("Starting scheduled dividend data and rank refresh...");
        try {
            // 1. Fetch latest dividend data (Last 1 Month)
            String endDate = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyyMMdd"));
            String startDate = LocalDate.now().minusMonths(1).format(DateTimeFormatter.ofPattern("yyyyMMdd"));

            dividendService.refreshAllDividends(startDate, endDate);

            // 2. Calculate Rank based on DB data
            dividendService.refreshDividendRank();
        } catch (Exception e) {
            log.error("Failed to refresh dividend data/rank: {}", e.getMessage());
        }
        log.info("Completed scheduled dividend data and rank refresh.");
    }

    // Run at 4 AM every Sunday (Financial Statements & Ratios)
    @Scheduled(cron = "0 0 4 * * SUN")
    public void updateWeeklyFinancialData() {
        log.info("Starting scheduled weekly financial data update...");
        try {
            // 1. Balance Sheet (Yearly)
            kisInformationService.refreshAllBalanceSheets("0");
            Thread.sleep(1000);

            // 2. Income Statement (Yearly)
            kisInformationService.refreshAllIncomeStatements("0");
            Thread.sleep(1000);

            // 3. Financial Ratios (Yearly)
            kisInformationService.refreshAllFinancialRatios("0");
            Thread.sleep(1000);

            // 4. Update Financial Rank (Based on updated Income Statements)
            kisInformationService.refreshFinancialRank();

        } catch (Exception e) {
            log.error("Failed to update weekly financial data: {}", e.getMessage());
        }
        log.info("Completed scheduled weekly financial data update.");
    }

    // Run every 1 minute from 9 AM to 3:59 PM (Market Hours) on Weekdays
    @Scheduled(cron = "0 * 9-15 * * MON-FRI")
    public void warmupMarketCapPrices() {
        log.info("Starting scheduled Top 100 Market Cap price warmup...");
        try {
            kisStockService.refreshTopMarketCapPrices();
        } catch (Exception e) {
            log.error("Failed to warmup market cap prices: {}", e.getMessage());
        }
    }
}
